language: python
python:
 - 3.5
notifications:
  email: false
before_install:
  # Setup anaconda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda
  # Edit the environment.yml file for the target Python version
  - sed -i -E 's/(python=)(.*)/\1'$TRAVIS_PYTHON_VERSION'/' ./environment.yml
  #Create the test environment python
  - conda env create -n testenv -f environment.yml
  - source activate testenv
  - pip install ase
  - pip install pycp2k
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda.
  #Except they themselves caused a crash recently, hence removed for now since no multiprocessing is done
#  - sudo rm -rf /dev/shm
#  - sudo ln -s /run/shm /dev/shm
install:
  - echo $TRAVIS_PYTHON_VERSION
  - python setup.py install
script:
  - cd test;python3 run_all_unit_tests.py
