langauge: python
python:
 - "3.5"
script:
  - virtualenv --python=python venv
  - source venv/bin/activate
  - python -m pip install -U pip
  - pip install -U wheel
  - pip install numpy
  - cd test;python3 run_all_unit_tests.py
